"""tabela url

Revision ID: 4726cef7ad41
Revises: 
Create Date: 2021-04-29 13:24:42.547838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4726cef7ad41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('ip_atual', sa.String(length=15), nullable=True),
    sa.Column('ip_novo', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_ip_atual'), 'url', ['ip_atual'], unique=False)
    op.create_index(op.f('ix_url_ip_novo'), 'url', ['ip_novo'], unique=False)
    op.create_index(op.f('ix_url_nome'), 'url', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_nome'), table_name='url')
    op.drop_index(op.f('ix_url_ip_novo'), table_name='url')
    op.drop_index(op.f('ix_url_ip_atual'), table_name='url')
    op.drop_table('url')
    # ### end Alembic commands ###
