"""coluna ip de que deve

Revision ID: 72d643812281
Revises: 4726cef7ad41
Create Date: 2021-04-30 12:27:28.362207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d643812281'
down_revision = '4726cef7ad41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('ip_que_deve_ser', sa.String(length=15), nullable=True))
    op.create_index(op.f('ix_url_ip_que_deve_ser'), 'url', ['ip_que_deve_ser'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_ip_que_deve_ser'), table_name='url')
    op.drop_column('url', 'ip_que_deve_ser')
    # ### end Alembic commands ###
